M48
; DRILL file {KiCad 9.0.7} date 2026-04-01T09:11:17-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-01T09:11:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X69.0Y-95.15
X69.0Y-99.85
T2
X69.347Y-57.66
X124.653Y-99.34
M30
