/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "can_ctrl.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	can_ctrl_init();

	while (1) {
	  can_ctrl_poll();
	}

}
#include "mcp_port.h"

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	(void)GPIO_Pin;
	  // Later: when you know the INT pin macro from main.h, you’ll do:
	  // if (GPIO_Pin == MCP_INT_Pin) { mcp_port_notify_irq(); }
}

